import { AlertTriangle, Bot, Code2, Eye, Network } from "lucide-react";
import { architectureLabel, decisionLabel, operationText, viewLabel } from "../lib/format";
import type { Suggestion } from "../types";

export function SuggestionList({
  suggestions,
  selected,
  onSelect,
}: {
  suggestions: Suggestion[];
  selected: string;
  onSelect: (id: string) => void;
}) {
  return (
    <div className="suggestion-list" aria-label="Generated remediation suggestions">
      {suggestions.map((suggestion, index) => (
        <button
          key={suggestion.finding_id}
          type="button"
          onClick={() => onSelect(suggestion.finding_id)}
          className={selected === suggestion.finding_id ? "selected" : ""}
        >
          <span className="suggestion-number">{String(index + 1).padStart(2, "0")}</span>
          <span className="suggestion-title">
            <small>
              {suggestion.rule_id} ·{" "}
              {architectureLabel(suggestion.model_evidence?.architecture || "")} ·{" "}
              {viewLabel(suggestion.model_evidence?.graph_view || "")}
            </small>
            <strong>{suggestion.help || suggestion.rule_id.replaceAll("-", " ")}</strong>
            <code>{suggestion.target.join(", ") || "page"}</code>
          </span>
          <span className={`decision decision-${suggestion.decision || "failed"}`}>
            {decisionLabel(suggestion)}
          </span>
        </button>
      ))}
    </div>
  );
}

export function SuggestionDetail({ suggestion }: { suggestion: Suggestion }) {
  if (suggestion.generation_status === "failed") {
    return (
      <div className="suggestion-detail error-detail">
        <AlertTriangle />
        <h3>The model did not return a suggestion</h3>
        <p>{suggestion.error}</p>
      </div>
    );
  }

  return (
    <article className="suggestion-detail">
      <div className="detail-heading">
        <div>
          <span className="section-label">LLM SUGGESTION</span>
          <h2>{suggestion.help || suggestion.rule_id}</h2>
        </div>
        <div className="confidence">
          <small>LLM self-confidence</small>
          <strong>{Math.round((suggestion.confidence || 0) * 100)}%</strong>
        </div>
      </div>
      <p className="rationale">{suggestion.rationale}</p>
      {suggestion.model_evidence && (
        <div className="gnn-evidence">
          <div>
            <Network size={18} />
            <span>
              <small>TRAINED SPECIALIST</small>
              <strong>
                {architectureLabel(suggestion.model_evidence.architecture)} ·{" "}
                {viewLabel(suggestion.model_evidence.graph_view)}
              </strong>
            </span>
          </div>
          <div className="probability">
            <span
              style={{ width: `${Math.max(2, suggestion.model_evidence.probability * 100)}%` }}
            />
            <i style={{ left: `${Math.min(99, suggestion.model_evidence.threshold * 100)}%` }} />
          </div>
          <div className="probability-labels">
            <span>Probability {(suggestion.model_evidence.probability * 100).toFixed(1)}%</span>
            <span>Frozen threshold {(suggestion.model_evidence.threshold * 100).toFixed(1)}%</span>
            <span>Routed: {suggestion.model_evidence.routing_status.replaceAll("_", " ")}</span>
          </div>
        </div>
      )}
      {(suggestion.operations || []).length > 0 && (
        <div className="operations">
          <h3>
            <Code2 size={17} />
            Proposed operations
          </h3>
          {suggestion.operations?.map((operation, index) => (
            <div className="operation" key={`${operation.operation}-${index}`}>
              <span>{index + 1}</span>
              <div>
                <strong>{operationText(operation)}</strong>
                <code>{operation.selector}</code>
              </div>
            </div>
          ))}
        </div>
      )}
      {suggestion.requires_human_review && (
        <div className="review-box">
          <Eye size={18} />
          <div>
            <strong>Human judgement required</strong>
            {suggestion.human_review_reasons?.map((reason) => (
              <p key={reason}>{reason}</p>
            ))}
          </div>
        </div>
      )}
      <div className="expected">
        <strong>Expected resolution</strong>
        <p>{suggestion.expected_resolution}</p>
      </div>
      <details>
        <summary>Validation checklist</summary>
        <ol>
          {suggestion.validation_steps?.map((step) => (
            <li key={step}>{step}</li>
          ))}
        </ol>
      </details>
      <div className="model-proof">
        <Bot size={16} />
        <span>
          Generated by <strong>{suggestion.model}</strong>
        </span>
        {suggestion.response_id && <code>{suggestion.response_id}</code>}
      </div>
    </article>
  );
}
