"""Versioned feature-layout constants shared by cache and ablation checks."""

RENDERED_VISUAL_FEATURE_VERSION = 2
STRUCTURAL_ATTRIBUTE_DIM = 113
RENDERED_VISUAL_ATTRIBUTE_DIM = 20
TEXT_EMBEDDING_DIM = 384
MINIMUM_RENDERED_FEATURE_DIM = STRUCTURAL_ATTRIBUTE_DIM + RENDERED_VISUAL_ATTRIBUTE_DIM + TEXT_EMBEDDING_DIM
